### PR TITLE
Update to new JSON messaging standard

### PR DESCRIPTION
**Pull request by jhobz**
See https://github.com/LiveSplit/LiveSplit.Server/pull/39 for more
 details.

Also fixes a bug (or rather just weird edge case interaction) with the socket data listener where multiple messages would get combined into one at very fast polling rates. I was able to run `.getAll()` every 5ms without errors at my fastest testing with these changes.

### CODE REVIEW

**Comment by satanch** [comment]
Thank you for your PR!
I need some time to check this.

**Comment by satanch** [comment]
Also, new LiveSplit server version must be released before I merge this into main branch.

**Comment by jhobz** [comment]
Yeah, for sure, no worries!

**Comment by satanch** [comment]
This PR is pretty outdated. Let's coma back to this issue when server changes would be applied.

**Pull request closed without merging**
